language: node_js
node_js:
  - "11.10.0"
sudo: required
services:
  - docker

before_install:
  - docker build -t farhansajid2/docker-react -f Dockerfile.dev .

scripts:
  - docker run farhansajid2/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name:
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
